#
# OpenSSL/crypto/sm4/Makefile
#

DIR=	sm4
TOP=	../..
CC=	cc
CPP=	$(CC) -E
INCLUDES=
CFLAG=-g
MAKEFILE=	Makefile
AR=		ar r

CFLAGS= $(INCLUDES) $(CFLAG)
ASFLAGS= $(INCLUDES) $(ASFLAG)
AFLAGS= $(ASFLAGS)

GENERAL=Makefile
TEST=sm4test.c
APPS=

LIB=$(TOP)/libcrypto.a
LIBSRC=sm4.c sm4_cbc.c sm4_cfb.c sm4_ofb.c sm4_ctr.c sm4_gcm.c sm4_wrap.c e_sm4.c
LIBOBJ=sm4.o sm4_cbc.o sm4_cfb.o sm4_ofb.o sm4_ctr.o sm4_gcm.o sm4_wrap.o e_sm4.o

SRC= $(LIBSRC)

EXHEADER= sm4.h
HEADER=	$(EXHEADER)

ALL=    $(GENERAL) $(SRC) $(HEADER)

top:
	(cd ../..; $(MAKE) DIRS=crypto SDIRS=$(DIR) sub_all)

all:	lib

lib:	$(LIBOBJ)
	$(AR) $(LIB) $(LIBOBJ)
	$(RANLIB) $(LIB) || echo Never mind.
	@touch lib

files:
	$(PERL) $(TOP)/util/files.pl Makefile >> $(TOP)/MINFO

links:
	@$(PERL) $(TOP)/util/mklink.pl ../../include/openssl $(EXHEADER)
	@$(PERL) $(TOP)/util/mklink.pl ../../test $(TEST)
	@$(PERL) $(TOP)/util/mklink.pl ../../apps $(APPS)

install:
	@[ -n "$(INSTALLTOP)" ] # should be set by top Makefile...
	@headerlist="$(EXHEADER)"; for i in $$headerlist ; \
	do  \
	(cp $$i $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i; \
	chmod 644 $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i ); \
	done;

tags:
	ctags $(SRC)

tests:

lint:
	lint -DLINT $(INCLUDES) $(SRC)>fluff

depend:
	@[ -n "$(MAKEDEPEND)" ] # should be set by upper Makefile...
	$(MAKEDEPEND) -- $(CFLAG) $(INCLUDES) $(DEPFLAG) -- $(PROGS) $(LIBSRC)

dclean:
	$(PERL) -pe 'if (/^# DO NOT DELETE THIS LINE/) {print; exit(0);}' $(MAKEFILE) >Makefile.new
	mv -f Makefile.new $(MAKEFILE)

clean:
	rm -f *.s *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff

# DO NOT DELETE THIS LINE -- make depend depends on it.
sm4.o: ../../include/openssl/opensslconf.h ../../include/openssl/opensslv.h
sm4.o: ../../include/openssl/sm4.h sm4.c
sm4_cbc.o: ../../include/openssl/sm4.h ../../include/openssl/modes.h
sm4_cbc.o: ../../include/openssl/opensslconf.h sm4_cbc.c
sm4_cfb.o: ../../include/openssl/sm4.h ../../include/openssl/modes.h
sm4_cfb.o: ../../include/openssl/opensslconf.h sm4_cfb.c
sm4_ofb.o: ../../include/openssl/sm4.h ../../include/openssl/modes.h
sm4_ofb.o: ../../include/openssl/opensslconf.h sm4_ofb.c
sm4_ctr.o: ../../include/openssl/sm4.h ../../include/openssl/modes.h
sm4_ctr.o: ../../include/openssl/opensslconf.h sm4_ctr.c
sm4_gcm.o: ../../include/openssl/crypto.h ../../include/openssl/e_os2.h
sm4_gcm.o: ../../include/openssl/modes.h ../../include/openssl/opensslconf.h
sm4_gcm.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
sm4_gcm.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
sm4_gcm.o: ../../include/openssl/sm4.h
sm4_gcm.o: ../../include/openssl/symhacks.h sm4_gcm.c 
sm4_wrap.o: ../../e_os.h ../../include/openssl/sm4.h
sm4_wrap.o: ../../include/openssl/bio.h ../../include/openssl/buffer.h
sm4_wrap.o: ../../include/openssl/crypto.h ../../include/openssl/e_os2.h
sm4_wrap.o: ../../include/openssl/err.h ../../include/openssl/lhash.h
sm4_wrap.o: ../../include/openssl/opensslconf.h
sm4_wrap.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
sm4_wrap.o: ../../include/openssl/safestack.h ../../include/openssl/stack.h
sm4_wrap.o: ../../include/openssl/symhacks.h ../cryptlib.h sm4_wrap.c

e_sm4.o: ../../include/openssl/sm4.h ../../include/openssl/asn1.h
e_sm4.o: ../../include/openssl/bio.h ../../include/openssl/crypto.h
e_sm4.o: ../../include/openssl/e_os2.h ../../include/openssl/err.h
e_sm4.o: ../../include/openssl/evp.h ../../include/openssl/lhash.h
e_sm4.o: ../../include/openssl/modes.h ../../include/openssl/obj_mac.h
e_sm4.o: ../../include/openssl/objects.h ../../include/openssl/opensslconf.h
e_sm4.o: ../../include/openssl/opensslv.h ../../include/openssl/ossl_typ.h
e_sm4.o: ../../include/openssl/rand.h ../../include/openssl/safestack.h
e_sm4.o: ../../include/openssl/stack.h ../../include/openssl/symhacks.h
e_sm4.o: ../modes/modes_lcl.h e_sm4.c 